# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_comments_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='total_seasons',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
    ]
